#!/usr/bin/env ../../../_dev/python_env/.venv/bin/python

import os
import json
import re

import chompjs

import requests

cwd = os.path.dirname(os.path.realpath(__file__))
os.chdir(cwd)

langs = []
base_dir=os.path.abspath(f"{cwd}/dist")

def save(name, url):
    print(name)
    r = requests.get(url)
    r.raise_for_status()
    with open(f"{base_dir}/{name}", 'wb') as f:
        f.write(r.content)

locale_code = json.loads(open("dist/locale.json").read())


#proc = subprocess.run("../../../_dev/js_env/bin/json-to-go",
#                      shell=True, capture_output=True, check=True,
#                      input=json.dumps(locale_code['af']).encode('utf-8'))
#with open(f"{cwd}/locale/api.go", 'wb') as f:
#    f.write(b"package locale\n\n")
#    f.write(proc.stdout.replace(b"type AutoGenerated ", b"type Messages ", 1))
#exit(0)

with open("vuetifyjs/package.json") as f:
    version = json.load(f)["dependencies"]['vuetify'][1:]
    # (f"https://github.com/vuetifyjs/vuetify/raw/refs/tags/v{version}/packages/vuetify/src/locale"
    r = requests.get(f"https://api.github.com/repos/vuetifyjs/vuetify/contents/packages/vuetify/src/locale?ref=v{version}",
                     headers={"Accept": "application/vnd.github.raw+json"})
    if r.status_code == 200:
       for f in r.json():
           if f['name'][2] in ['.', '-']:
               name = f['name'][:-3]
               r = requests.get(f['download_url'])
               print(name)
               if r.status_code == 200:
                   raw = re.sub(r',\s*([}\]])', r'\1', r.text.replace('export default ', ''))
                   langs.append(f"'{name}': {raw}")
    else:
        raise BaseException(f"Request failed with status code: {r.status_code}")

    python_dict = chompjs.parse_js_object("{\n" + ",\n".join(langs) + "\n}")
    locale_code = json.dumps(python_dict, indent=2)
    with open(f"{base_dir}/locale.json", "w") as f:
        f.write(locale_code)

    exit(0)

    for name in [
        "vuetify.min.js",
        "vuetify.min.css",
        "vuetify-labs.min.js",
        "vuetify-labs.min.css",
    ]:
        save(name, f"https://cdn.jsdelivr.net/npm/vuetify@{version}/dist/{name}")