/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSelect: typeof import('./src/lib/AdvancedSelect.vue')['default']
    Autocomplete: typeof import('./src/lib/Autocomplete.vue')['default']
    AutoCompleteExample: typeof import('./src/demo/components/AutoCompleteExample.vue')['default']
    Card: typeof import('./src/lib/Card.vue')['default']
    DateItem: typeof import('./src/lib/Filter/components/DateItem.vue')['default']
    Datepicker: typeof import('./src/lib/Datepicker.vue')['default']
    DatepickerExample: typeof import('./src/demo/components/DatepickerExample.vue')['default']
    DateRangeItem: typeof import('./src/lib/Filter/components/DateRangeItem.vue')['default']
    Datetimepicker: typeof import('./src/lib/Datetimepicker.vue')['default']
    DatetimepickerExample: typeof import('./src/demo/components/DatetimepickerExample.vue')['default']
    DatetimeRangeItem: typeof import('./src/lib/Filter/components/DatetimeRangeItem.vue')['default']
    DefaultNavigatorExample: typeof import('./src/demo/components/DefaultNavigatorExample.vue')['default']
    Dialog: typeof import('./src/lib/Dialog.vue')['default']
    DragListener: typeof import('./src/lib/DragListener.vue')['default']
    DragListenerExample: typeof import('./src/demo/components/DragListenerExample.vue')['default']
    EditorJS: typeof import('./src/lib/EditorJS/EditorJS.vue')['default']
    Filter: typeof import('./src/lib/Filter/index.vue')['default']
    FilterButton: typeof import('./src/lib/Filter/components/FilterButton.vue')['default']
    FilterButtonBody: typeof import('./src/lib/Filter/components/FilterButtonBody.vue')['default']
    FilterExample: typeof import('./src/demo/components/FilterExample.vue')['default']
    HelloWorld: typeof import('./src/demo/components/HelloWorld.vue')['default']
    ItemFilter: typeof import('./src/lib/Filter/components/ItemFilter.vue')['default']
    LinkageSelect: typeof import('./src/lib/LinkageSelect.vue')['default']
    LinkageSelectExample: typeof import('./src/demo/components/LinkageSelectExample.vue')['default']
    LinkageSelectItem: typeof import('./src/lib/Filter/components/LinkageSelectItem.vue')['default']
    MessageListener: typeof import('./src/lib/MessageListener.vue')['default']
    MonthItem: typeof import('./src/lib/Filter/components/MonthItem.vue')['default']
    Monthpicker: typeof import('./src/lib/Monthpicker.vue')['default']
    MonthRangeItem: typeof import('./src/lib/Filter/components/MonthRangeItem.vue')['default']
    MultipleSelectItem: typeof import('./src/lib/Filter/components/MultipleSelectItem.vue')['default']
    NavigationDrawer: typeof import('./src/lib/NavigationDrawer.vue')['default']
    NumberItem: typeof import('./src/lib/Filter/components/NumberItem.vue')['default']
    RestoreScrollListener: typeof import('./src/lib/RestoreScrollListener.vue')['default']
    ScrollIframe: typeof import('./src/lib/ScrollIframe.vue')['default']
    ScrollIframeExample: typeof import('./src/demo/components/ScrollIframeExample.vue')['default']
    SelectItem: typeof import('./src/lib/Filter/components/SelectItem.vue')['default']
    SendVariables: typeof import('./src/lib/SendVariables.vue')['default']
    SendVariablesExample: typeof import('./src/demo/components/SendVariablesExample.vue')['default']
    StringItem: typeof import('./src/lib/Filter/components/StringItem.vue')['default']
    TextDatepicker: typeof import('./src/lib/TextDatepicker.vue')['default']
    TextDatepickerExample: typeof import('./src/demo/components/TextDatepickerExample.vue')['default']
    TreeDataTable: typeof import('./src/lib/TreeDataTable.vue')['default']
    TreeDataTableExample: typeof import('./src/demo/components/TreeDataTableExample.vue')['default']
    TreeRows: typeof import('./src/lib/TreeRows.vue')['default']
    Videojs: typeof import('./src/lib/EditorJS/Videojs.vue')['default']
  }
}
